# Generated by Django 3.1.6 on 2021-02-04 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=31)),
                ('env', models.CharField(max_length=31)),
                ('name', models.CharField(max_length=31)),
                ('desc', models.CharField(max_length=127)),
                ('download_url', models.CharField(max_length=255)),
                ('display_image', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=63)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
